import 'package:customer_app/features/vehicles/domain/vehicle.dart';

List<Vehicle> buildVehicleTestVehicles() {
  return [
    Vehicle(
      id: 'toyota-rav4-2021',
      make: 'Toyota',
      model: 'RAV4',
      year: 2021,
      condition: VehicleCondition.used,
      price: 24900,
      odometerKm: 48000,
      bodyType: 'SUV',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      location: 'King Auto - Rocklea, QLD 4106',
      images: ['assets/images/vehicles/toyota_rav4.jpg'],
      isNewArrival: false,
      engineHealthPercent: 92,
      oilWarningStatus: VehicleOilWarningStatus.off,
      publishedAt: DateTime(2026, 8, 20, 9, 0),
    ),
    Vehicle(
      id: 'bmw-320i-2019',
      make: 'BMW',
      model: '320i',
      year: 2019,
      condition: VehicleCondition.damaged,
      price: 22500,
      odometerKm: 72000,
      bodyType: 'Sedan',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      location: 'King Auto - Rocklea, QLD 4106',
      images: ['assets/images/vehicles/damaged_bmw.jpg'],
      isNewArrival: false,
      engineHealthPercent: 64,
      oilWarningStatus: VehicleOilWarningStatus.on,
      publishedAt: DateTime(2026, 8, 18, 14, 30),
    ),
    Vehicle(
      id: 'toyota-land-cruiser-2025',
      make: 'Toyota',
      model: 'Land Cruiser',
      year: 2025,
      condition: VehicleCondition.newVehicle,
      price: 89900,
      odometerKm: 20,
      bodyType: 'SUV',
      transmission: 'Automatic',
      fuelType: 'Diesel',
      location: 'King Auto - Rocklea, QLD 4106',
      images: ['assets/images/new_arrivals/new_land_cruiser.jpg'],
      isNewArrival: true,
      engineHealthPercent: 99,
      oilWarningStatus: VehicleOilWarningStatus.off,
      publishedAt: DateTime(2026, 8, 26, 16, 0),
    ),
    Vehicle(
      id: 'audi-suv-2025',
      make: 'Audi',
      model: 'SUV',
      year: 2025,
      condition: VehicleCondition.newVehicle,
      price: 74900,
      odometerKm: 15,
      bodyType: 'SUV',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      location: 'King Auto - Rocklea, QLD 4106',
      images: ['assets/images/new_arrivals/new_audi_suv.jpg'],
      isNewArrival: true,
      engineHealthPercent: 97,
      oilWarningStatus: VehicleOilWarningStatus.off,
      publishedAt: DateTime(2026, 8, 26, 17, 30),
    ),
  ];
}
